name: Create Changelog and merge back

on:
  push:
    branches:
      - main
jobs:
  release_change_log:
    name: Update CHANGELOG file
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          package-name: release-please-action
          default-branch: main
          labels: automerge
  merge_change_log:
    needs: release_change_log
    runs-on: ubuntu-latest
    env:
      PRID: ""
    steps:
      - run: echo start automerge...; PRID=$(gh pr list -R WinnersProx/github-cli-demo --label automerge | cut -f 1); echo Pending PR $PRID; if [[ "$PRID" -ne "" ]]; then gh pr merge $PRID -R WinnersProx/github-cli-demo --admin -m -d; fi; echo done;
        env:
          GH_TOKEN: ${{ secrets.GH_API_KEY }}
      - run: echo last PR $PRID;
      
